# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quantileC <- function(Tstatvec, alpha) {
    .Call('_SpLoc_quantileC', PACKAGE = 'SpLoc', Tstatvec, alpha)
}

set_seed <- function(seed) {
    invisible(.Call('_SpLoc_set_seed', PACKAGE = 'SpLoc', seed))
}

SpLocMeanC <- function(ymat, NNmatrix, nperm, alpha, s) {
    .Call('_SpLoc_SpLocMeanC', PACKAGE = 'SpLoc', ymat, NNmatrix, nperm, alpha, s)
}

SpLocDiffC <- function(ymat, NNmatrix, group, nperm, alpha, s) {
    .Call('_SpLoc_SpLocDiffC', PACKAGE = 'SpLoc', ymat, NNmatrix, group, nperm, alpha, s)
}

