# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quantileC <- function(Tstatvec, alpha) {
    .Call('_SpLoc_quantileC', PACKAGE = 'SpLoc', Tstatvec, alpha)
}

invNT <- function(u, x) {
    .Call('_SpLoc_invNT', PACKAGE = 'SpLoc', u, x)
}

set_seed <- function(seed) {
    invisible(.Call('_SpLoc_set_seed', PACKAGE = 'SpLoc', seed))
}

SpLocMeanC <- function(ymat, NNmatrix, nperm, alpha, s, side) {
    .Call('_SpLoc_SpLocMeanC', PACKAGE = 'SpLoc', ymat, NNmatrix, nperm, alpha, s, side)
}

SpLocDiffC <- function(ymat, NNmatrix, group, nperm, alpha, s, side) {
    .Call('_SpLoc_SpLocDiffC', PACKAGE = 'SpLoc', ymat, NNmatrix, group, nperm, alpha, s, side)
}

MassiveMeanC <- function(ymat, nperm, alpha, s, side) {
    .Call('_SpLoc_MassiveMeanC', PACKAGE = 'SpLoc', ymat, nperm, alpha, s, side)
}

MassiveDiffC <- function(ymat, group, nperm, alpha, s, side) {
    .Call('_SpLoc_MassiveDiffC', PACKAGE = 'SpLoc', ymat, group, nperm, alpha, s, side)
}

